Aprendendo Pandas - Comandos

In [14]:
# apelido para falicitar a escrita
import pandas as pd

In [18]:
#dataframe = pd.DataFrame () -> É uma tabela dentro do Python

#criando um dicionario
cliente = {
    'nome': ['Diogo Rosa', 'Eric Santos', 'Manuela Garcia'],
    'e-mail': ['diogo@gmail.com', 'eric@gmail.com', 'manuela@gmail.com'],
    'idade': [21, 27, 15],
}

print(cliente) #visualizar o dicionario

#df para identificar que é um dataframe -> criando um DataFrame
cliente_df = pd.DataFrame(cliente)

display(cliente_df)

{'nome': ['Diogo Rosa', 'Eric Santos', 'Manuela Garcia'], 'e-mail': ['diogo@gmail.com', 'eric@gmail.com', 'manuela@gmail.com'], 'idade': [21, 27, 15]}

             nome             e-mail  idade
0      Diogo Rosa    diogo@gmail.com     21
1     Eric Santos     eric@gmail.com     27
2  Manuela Garcia  manuela@gmail.com     15

In [23]:
#importar a partir de uma base de dados

table_df = pd.read_excel('base_dados_orcamento.xlsx')
display(table_df)

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94

In [25]:
# metodo head -> mostra apenas as 5 primeiras linhas da sua base
# se quiser visualizar mais é só colocar a qnt dentro do () -> .head(15)

display(table_df.head())

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98

In [27]:
#metodo shape -> mostra a qntd de linhas e colunas da sua tabela e *não usa ()*

print(table_df.shape)

# comanfo decribe -> mostra o resumo numérico
display(table_df.describe())

(20, 8)

,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado
count,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000
mean,3.300000,146.491000,400.718000,3.70000,146.491000,448.214500
std,1.592747,116.062628,352.310585,2.05452,116.062628,351.496738
min,1.000000,15.990000,79.950000,1.00000,15.990000,79.950000
25%,2.000000,87.490000,114.992500,2.00000,87.490000,118.477500
50%,4.000000,99.990000,314.980000,3.00000,99.990000,389.960000
75%,5.000000,249.992500,496.202500,5.00000,249.992500,729.920000
max,5.000000,379.990000,1279.960000,8.00000,379.990000,1139.970000

In [28]:
#visualizar coluna espeficia
produto = table_df[['Produto']
display(produto) #não é um DataFrame -> pd.Series

0             Cadeira Corte
1             Cadeira Corte
2           poltrona espera
3           poltrona espera
4                 lavatório
5                 lavatório
6                   espelho
7                   espelho
8     estuda esterilizadora
9     estuda esterilizadora
10             kit tesouras
11             kit tesouras
12                  secador
13                  secador
14                 chapinha
15                 chapinha
16                    pente
17                    pente
18                   escova
19                   escova
Name: Produto, dtype: object

In [29]:
#visualizar coluna espeficia
produto = table_df[['Produto', 'Fornecedor']]
display(produto) #tabel que veio da tabla original

                  Produto     Fornecedor
0           Cadeira Corte    Week Beauty
1           Cadeira Corte  Beleza em Dia
2         poltrona espera    Week Beauty
3         poltrona espera  Beleza em Dia
4               lavatório    Week Beauty
5               lavatório  Beleza em Dia
6                 espelho    Week Beauty
7                 espelho  Beleza em Dia
8   estuda esterilizadora    Week Beauty
9   estuda esterilizadora  Beleza em Dia
10           kit tesouras    Week Beauty
11           kit tesouras  Beleza em Dia
12                secador    Week Beauty
13                secador  Beleza em Dia
14               chapinha    Week Beauty
15               chapinha  Beleza em Dia
16                  pente    Week Beauty
17                  pente  Beleza em Dia
18                 escova    Week Beauty
19                 escova  Beleza em Dia

In [32]:
#visualizar linha espeficia - metodo loc[] a count inicia com 0
display(cliente_df.loc[0:3])

             nome             e-mail  idade
0      Diogo Rosa    diogo@gmail.com     21
1     Eric Santos     eric@gmail.com     27
2  Manuela Garcia  manuela@gmail.com     15

In [41]:
#visualizar todas as linha que correspondem a uma condição - comando loc.
fornecedor_weekbeauty_df = display(table_df.loc[table_df['Fornecedor'] == 'Week Beauty']) # fornecedo week beauty

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94

In [46]:
#visualizar várias linha e colunas que correspondem a uma condição, usando o comando loc.
#o comando loc é processado a seguinte ordem (linha e coluna) as linhas precisam de uma condição e as colunas apenas dos nomes
#comparando valores entre dois fornecedores
fornecedor_weekbeauty_df = table_df.loc[table_df['Produto'] == 'lavatório', ['Fornecedor','Valor à Planejado', 'Valor Realizado']]
display(fornecedor_weekbeauty_df)

      Fornecedor  Valor à Planejado  Valor Realizado
4    Week Beauty             199.98           199.98
5  Beleza em Dia             159.98           159.98

In [51]:
#visualizar apenas um dado com comando loc.
valor_especifico_df = table_df.loc[5, 'Produto']
display(valor_especifico_df)

'lavatório'

In [86]:
#criar uma coluna com valor padrão *sem o comando .loc*
table_df['Desconto'] = '3%'
#display (table_df)

#para preencher todas as linhas ou colunas é só colcoar : antes da condição *utilizando o comando .loc*
table_df.loc[:, 'Status'] = 0



#adicionar a partir de uma coluna que existe
table_df['Qnt Prod em Falta'] = table_df['Qnt Planejada'] + 1

display(table_df)

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado,Desconto,Status,Qnt Prod em Falta
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97,3%,0,3
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97,3%,0,3
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96,3%,0,5
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96,3%,0,5
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98,3%,0,3
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98,3%,0,3
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92,3%,0,6
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92,3%,0,6
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00,3%,0,2
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99,3%,0,2
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00,3%,0,2
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98,3%,0,2
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97,3%,0,5
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97,3%,0,5
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97,3%,0,5
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97,3%,0,5
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95,3%,0,6
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95,3%,0,6
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94,3%,0,6
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94,3%,0,6
Status,0,0,0,0.00,0.00,0,0.00,0.00,3%,0,1

In [76]:
#adicionar linha juntando outra base de dados
#nm_tabela1 = nm_tabela1.append('nm_tabela2')
#display(nm_tabela1)

In [88]:
#excluir coluna
#axis=1 -> eixo da coluna
#axis=0 -> eixo da linha
table_df = table_df.drop('Desconto', axis=1)
display(table_df)

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado,Status,Qnt Prod em Falta
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97,0,3
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97,0,3
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96,0,5
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96,0,5
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98,0,3
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98,0,3
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92,0,6
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92,0,6
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00,0,2
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99,0,2
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00,0,2
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98,0,2
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97,0,5
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97,0,5
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97,0,5
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97,0,5
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95,0,6
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95,0,6
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94,0,6
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94,0,6
Status,0,0,0,0.00,0.00,0,0.00,0.00,0,1

In [105]:
table_df = pd.read_excel('base_dados_orcamento.xlsx')
display(table_df)

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94

In [106]:
#adiconar uma coluna vazia para trata-lá
table_df.loc[:, 'Status'] = 0
display(table_df)

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado,Status
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97,0
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97,0
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96,0
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96,0
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98,0
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98,0
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92,0
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92,0
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00,0
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99,0
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00,0
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98,0
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97,0
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97,0
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97,0
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97,0
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95,0
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95,0
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94,0
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94,0

In [112]:
#deletando linhas e colunas completamente vazias - comando .drpna
#deletando apenas as linhas .dropna(how='all')
#deletando linhas e colunas .dropna(how='all', axis=1)
table_df = table_df.dropna(how='all', axis=1)
display(table_df)

#deletar linhas que possuem pelo menos 1 valor vazio
table_df = table-df.dropna()

#preencher valores vazios
table_df['Status'] = table_df['Status'].fillna(1)
display(table_df)

#preencher com o último valor de cima para baixo
table_df = table_df.ffill()

,Produto,Fornecedor,Qnt Planejada,Custo Planejado,Valor à Planejado,Qnt Realizada,Custo Realizado,Valor Realizado,Status
0,Cadeira Corte,Week Beauty,2,379.99,759.98,3,379.99,1139.97,0
1,Cadeira Corte,Beleza em Dia,2,339.99,679.98,3,339.99,1019.97,0
2,poltrona espera,Week Beauty,4,94.99,379.96,4,94.99,379.96,0
3,poltrona espera,Beleza em Dia,4,99.99,399.96,4,99.99,399.96,0
4,lavatório,Week Beauty,2,99.99,199.98,2,99.99,199.98,0
5,lavatório,Beleza em Dia,2,79.99,159.98,2,79.99,159.98,0
6,espelho,Week Beauty,5,94.99,474.95,8,94.99,759.92,0
7,espelho,Beleza em Dia,5,89.99,449.95,8,89.99,719.92,0
8,estuda esterilizadora,Week Beauty,1,100.00,100.00,1,100.00,100.00,0
9,estuda esterilizadora,Beleza em Dia,1,119.99,119.99,1,119.99,119.99,0
10,kit tesouras,Week Beauty,1,250.00,250.00,2,250.00,500.00,0
11,kit tesouras,Beleza em Dia,1,249.99,249.99,2,249.99,499.98,0
12,secador,Week Beauty,4,139.99,559.96,3,139.99,419.97,0
13,secador,Beleza em Dia,4,99.99,399.96,3,99.99,299.97,0
14,chapinha,Week Beauty,4,299.99,1199.96,3,299.99,899.97,0
15,chapinha,Beleza em Dia,4,319.99,1279.96,3,319.99,959.97,0
16,pente,Week Beauty,5,18.99,94.95,5,18.99,94.95,0
17,pente,Beleza em Dia,5,15.99,79.95,5,15.99,79.95,0
18,escova,Week Beauty,5,18.99,94.95,6,18.99,113.94,0
19,escova,Beleza em Dia,5,15.99,79.95,6,15.99,95.94,0

In [117]:
#comando value counts

total_qntd_planejada = table_df['Qnt Planejada'].value_counts()
display(total_qntd_planejada)

#comando groupby
faturamento_realizado = table_df[['Produto', 'Valor Realizado']].groupby('Produto').sum()
display(faturamento_realizado)

4    6
5    6
2    4
1    4
Name: Qnt Planejada, dtype: int64

                       Valor Realizado
Produto
Cadeira Corte                  2159.94
chapinha                       1859.94
escova                          209.88
espelho                        1479.84
estuda esterilizadora           219.99
kit tesouras                    999.98
lavatório                       359.96
pente                           174.90
poltrona espera                 779.92
secador                         719.94

In [ ]:
#metodo mesclar - comando merge

table_gerente_df = pd.read_excel('gerente.xlsx')
display(table_gerente)

table_df = table_df.merge(table_gerente_df)
display(able_df)